package dev.t1m3.qplayer.desktop.aot;

import dev.t1m3.qplayer.desktop.*;
import io.github.timer_err.qml4j.engine.QmlEngine;
import io.github.timer_err.qml4j.render.QmlView;
import io.github.timer_err.qml4j.render.ResourceLoader;

import dev.t1m3.qplayer.audio.AudioBackend;
import dev.t1m3.qplayer.audio.MetadataReader;
import dev.t1m3.qplayer.bridge.PlayerController;
import dev.t1m3.qplayer.lyric.skia.Fonts;
import dev.t1m3.qplayer.util.Logger;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * Build-time AOT compiler. Wires the same engine/view the desktop host builds, but
 * with an {@link AotDumpBackend}, then runs one {@code view.load(Main.qml)} — which
 * compiles the whole reachable QML graph (root + pages + md3 components + inline
 * components + singletons) and writes every generated class to disk. Those classes
 * are then put on the classpath so {@link PrecompiledBackend} loads them at runtime
 * and GraalVM native-image can include them ahead of time.
 *
 * <p>Run with the desktop runtime classpath:
 * {@code java ... dev.t1m3.qplayer.desktop.aot.AotCompile <out-dir>}.
 */
public final class AotCompile {

    public static void main(String[] args) {
        Path outDir = Paths.get(args.length > 0 ? args[0]
                : System.getProperty("qplayer.aot.out", "target/aot-classes"));
        Logger.info("AOT: compiling QML → {}", outDir.toAbsolutePath());

        ResourceLoader resources = new ClasspathResourceLoader();
        Fonts.init(
                resources.load("fonts/PingFangSC-Thin.otf"),
                resources.load("fonts/PingFangSC-Light.otf"),
                resources.load("fonts/PingFangSC-Regular.otf"),
                resources.load("fonts/PingFangSC-Medium.otf")
        );
        Fonts.initIcon(resources.load("fonts/MaterialSymbolsRounded.ttf"));

        AudioBackend audio = new DesktopAudioBackend();
        MetadataReader reader = new DesktopMetadataReader();
        PlayerController controller = new PlayerController(audio, reader);
        controller.setColorExtractor(new DesktopColorExtractor());
        DesktopSettings settings = new DesktopSettings();
        settings.load();

        byte[] qmlBytes = resources.load("Main.qml");
        if (qmlBytes == null) throw new IllegalStateException("Main.qml not found on classpath");
        String qml = new String(qmlBytes, StandardCharsets.UTF_8);

        AotDumpBackend backend = new AotDumpBackend(outDir);
        QmlEngine engine = new QmlEngine(backend);
        QmlView view = QmlView.withStockTypes(engine).resources(resources);
        view.context("player", controller);
        view.context("settings", settings);
        DesktopWindow.loadFonts(view, resources);

        try {
            view.load(qml);
        } catch (Throwable t) {
            // Classes are dumped during compilation (before instantiation), so an
            // instantiation-time error still leaves a complete class set; surface it
            // but don't fail the dump.
            Logger.warn("AOT: view.load raised after compilation ({}): {}",
                    t.getClass().getSimpleName(), t.getMessage());
        }

        Logger.info("AOT: dumped {} classes", backend.dumpedCount());
        writeGeneratedReflectConfig(outDir, backend.dumpedNames());

        // Audio/AWT non-daemon threads would keep us alive; exit hard.
        Runtime.getRuntime().halt(0);
    }

    // Emit a reflect-config.json covering every generated QML class so native-image includes
    // them and PrecompiledBackend's Class.forName resolves them at runtime. Written under
    // target/classes/META-INF/native-image/** so it lands in the jar and native-image
    // auto-merges it — generated straight from the AOT dump, so a QML change that mints new
    // delegate classes can never leave a hand-kept reflect-config stale (the crash mode:
    // "No classes have been predefined during the image build to load from bytecodes").
    private static void writeGeneratedReflectConfig(Path outDir, java.util.List<String> names) {
        StringBuilder json = new StringBuilder("[\n");
        for (int i = 0; i < names.size(); i++) {
            // Constructors (root types are reflectively newInstance'd) + fields
            // (MemberAccess reads QML ids/props by name). NOT methods: generated-class
            // methods (_delegate$, binding bodies) are invoked by generated bytecode, so
            // normal reachability includes them — forcing allDeclaredMethods here only
            // bloats the points-to analysis (it OOM'd the image build).
            json.append("{\"name\":\"").append(names.get(i)).append("\",")
                .append("\"allDeclaredConstructors\":true,")
                .append("\"allDeclaredFields\":true}");
            json.append(i + 1 < names.size() ? ",\n" : "\n");
        }
        json.append("]\n");
        Path cfg = outDir.resolve("META-INF/native-image/dev.t1m3.qplayer/qml4j-generated/reflect-config.json");
        try {
            Files.createDirectories(cfg.getParent());
            Files.write(cfg, json.toString().getBytes(StandardCharsets.UTF_8));
            Logger.info("AOT: wrote reflect-config for {} generated classes", names.size());
        } catch (java.io.IOException e) {
            throw new IllegalStateException("failed writing AOT reflect-config", e);
        }
    }
}
